FROM alpine:3.8

WORKDIR /tmp
RUN apk add --no-cache curl
RUN curl https://dl.google.com/go/go1.11.4.src.tar.gz -o go1.11.4.src.tar.gz
RUN tar --extract --file=go1.11.4.src.tar.gz go/test/zerodivide.go
RUN rm go1.11.4.src.tar.gz
