FROM alpine:3.8

WORKDIR /tmp
RUN apk add --no-cache --virtual .build-deps curl \
    && curl https://raw.githubusercontent.com/stephanedaviet/prez-docker/master/files/big-archive.tgz -o big-archive.tgz \
    && tar zxvf big-archive.tgz \
    && rm big-archive.tgz \
    && rm -rf /tmp/big-archive \
    && apk del .build-deps
